### ISSUE TITLE
Build errors when run with --parallel 96

### ISSUE THREAD

**Issue by ferrreo** [quickshell-mirror/quickshell#10]
Not sure if you even want to support parallel builds but would make my builds like 1 min instead of 6 mins+ on the 96 thread build box I'm using. It builds fine not in parallel.

Here is the build log with the error:

https://git.pika-os.com/wm-packages/quickshell/actions/runs/22

**Comment by outfoxxed** [comment]
Parallel builds are supposed to work. I noticed a couple things in your logs though:
- spirv-tools is missing, iirc this can be ignored but it won't optimize shaders.
- pch seems to be somewhat broken on gcc again (will look at that one)
- make isn't handling dbus_properties.cpp

From that I'd try building with ninja, because this seems like an issue with make or cmake. Would recommend installing spirv-tools as well.

**Comment by ferrreo** [comment]
> Parallel builds are supposed to work. I noticed a couple things in your logs though:
> 
> * spirv-tools is missing, iirc this can be ignored but it won't optimize shaders.
> * pch seems to be somewhat broken on gcc again (will look at that one)
> * make isn't handling dbus_properties.cpp
> 
> From that I'd try building with ninja, because this seems like an issue with make or cmake. Would recommend installing spirv-tools as well.

ninja did indeed fix it, also added spirv-tools to the build-deps. 1min 10s for build including bootstrapping a clean docker container. Not bad at all! Closing.
